### ISSUE TITLE
travis encrypt --add deletes comments

### ISSUE THREAD

**Issue by MariadeAnton** [travis-ci/travis.rb#316] opened 2015-08-24 15:44 UTC
from customer feedback:
When using ``travis encrypt -a ``it not only adds a secure key but also *deletes* any comment lines in `.travis.yml` file.

**Comment by BanzaiMan** [comment] 2015-08-24 16:41
This is a duplicate of #144, which, unfortunately, is a WONTFIX.

**Closed by BanzaiMan** 2015-08-24 16:41 UTC
