### ISSUE TITLE
Encrypt blows up with "InvalidURIError: Invalid scheme format: git@github.com"

### ISSUE THREAD

**Issue by viraptor** [travis-ci/travis.rb#351] opened 2015-12-31 01:18 UTC
Running just `travis encrypt` results in:

```
An error occurred running `travis encrypt`:
    Addressable::URI::InvalidURIError: Invalid scheme format: git@github.com
        from /home/viraptor/.gem/ruby/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:867:in `scheme='
        from /home/viraptor/.gem/ruby/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:795:in `block in initialize'
        from /home/viraptor/.gem/ruby/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:2302:in `call'
        from /home/viraptor/.gem/ruby/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:2302:in `defer_validation'
        from /home/viraptor/.gem/ruby/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:792:in `initialize'
        from /home/viraptor/.gem/ruby/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:135:in `new'
        from /home/viraptor/.gem/ruby/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:135:in `parse'
        from /home/viraptor/.gem/ruby/2.2.0/gems/travis-1.8.0/lib/travis/cli/repo_command.rb:71:in `detect_slug'
        from /home/viraptor/.gem/ruby/2.2.0/gems/travis-1.8.0/lib/travis/cli/repo_command.rb:60:in `find_slug'
        from /home/viraptor/.gem/ruby/2.2.0/gems/travis-1.8.0/lib/travis/cli/repo_command.rb:21:in `setup'
        from /home/viraptor/.gem/ruby/2.2.0/gems/travis-1.8.0/lib/travis/cli/command.rb:197:in `execute'
        from /home/viraptor/.gem/ruby/2.2.0/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
        from /home/viraptor/.gem/ruby/2.2.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
        from /home/viraptor/.gem/ruby/2.2.0/bin/travis:23:in `load'
        from /home/viraptor/.gem/ruby/2.2.0/bin/travis:23:in `<main>'
```

**Comment by BanzaiMan** [comment] 2015-12-31 03:03
A duplicate of #342.

**Closed by BanzaiMan** 2015-12-31 03:03 UTC
