### ISSUE TITLE
logs command fails: undefined method `each_pair' for #<String:*> if the job has already finished and the logs archived

### ISSUE THREAD

**Issue by electrum** [travis-ci/travis.rb#578] opened 2018-02-09 02:39 UTC
```
[dphillips@imac:~/src/presto master] travis logs 29248.9
displaying logs for prestodb/presto#29248.9
undefined method `each_pair' for #<String:0x00007fd51a053e70>
Did you mean?  each_char
for a full error report, run travis report --org


[dphillips@imac:~/src/presto master] travis report --org
System
Ruby:                     Ruby 2.5.0-p0
Operating System:         Mac OS X 10.13.3
RubyGems:                 RubyGems 2.7.4

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2018-02-08 18:38:34 -0800

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "electrum"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `each_pair' for #<String:0x00007fd51a053e70>
Did you mean?  each_char
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/session.rb:139:in `load'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/session.rb:166:in `get'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/session.rb:319:in `fetch_one'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/session.rb:128:in `reload'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/entity.rb:208:in `load_attribute'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/entity.rb:194:in `relation'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/entity.rb:71:in `block (2 levels) in has'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/client/artifact.rb:51:in `body'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /Users/dphillips/homebrew/lib/ruby/gems/2.5.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /Users/dphillips/homebrew/bin/travis:23:in `load'
        from /Users/dphillips/homebrew/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.

**Comment by eupharis** [comment] 2018-02-09 17:20
I'm experiencing this as well.

**Comment by adigherman** [comment] 2018-02-09 17:21
I'm also seeing this on my end.

**Comment by cloudinary-misha** [comment] 2018-02-18 09:55
Hi I've also experience this issue, 
after small research:
issue occurs in client/session.rb => def load
argument data expected to be hash or empty, but string received instead.
`def load(data)
        result = {}
        (data || {}).each_pair do |key, value|
          entity      = load_entity(key, value)
          result[key] = entity if entity
        end
        result
      end`

**Comment by adigherman** [comment] 2018-02-27 16:25
Thanks @20goto10, I've added your patch to my local files and ran into:

`undefined method `pending?' for nil:NilClass
for a full error report, run travis report --org`

` NoMethodError: undefined method `pending?' for nil:NilClass
        from /usr/local/rvm/gems/ruby-2.1.8/gems/travis-1.8.8/lib/travis/client/artifact.rb:51:in `body'`

I commented `unless stream and job.pending?` on line #51 and now I'm getting the logs again. 

Hopefully they'll address this issue soon.

**Comment by 20goto10** [comment] 2018-02-27 17:54
@adigherman - Patch is a very kind word! This is solely a useful workaround (hack) I was able to slap together without needing to delve too deep into the rest of the Travis client code. 

It looks like that error would only come up if you're hitting the body method with a block for streaming larger logs. So, I'd double-check to make sure you're getting the whole log, and not just one chunk of it, after commenting out that line.

**Comment by danielpclark** [comment] 2018-03-05 14:16
I can verify the same issue comes up with `travis logs` and `travis logs .1`

**Comment by laanwj** [comment] 2018-03-06 15:00
Same error here while using `travis logs`:
```
System
Ruby:                     Ruby 2.3.3-p222
Operating System:         Ubuntu 17.10
RubyGems:                 RubyGems 2.5.2.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2018-03-06 15:57:09 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "laanwj"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `each_pair' for #<String:0x00558749d30470>
Did you mean?  each_char
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:139:in `load'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:166:in `get'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:319:in `fetch_one'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:128:in `reload'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:208:in `load_attribute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:194:in `relation'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:71:in `block (2 levels) in has'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/artifact.rb:51:in `body'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by thurt** [comment] 2018-03-30 17:06
I have this issue as well. it seems like it works sometimes and other times not.
```
System
Ruby:                     Ruby 2.3.3-p222
Operating System:         Linux
RubyGems:                 RubyGems 2.5.2.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2018-03-30 16:57:36 +0000

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "thurt"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `each_pair' for #<String:0x000095b3369298>
Did you mean?  each_char
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:139:in `load'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:166:in `get'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:319:in `fetch_one'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:128:in `reload'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:208:in `load_attribute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:194:in `relation'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:71:in `block (2 levels) in has'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/artifact.rb:51:in `body'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by iriberri** [comment] 2018-04-04 15:28
I could reproduce this locally in my macOS machine, and I ran the command with the `--debug` option to see which requests and at which point this was happening:

```
$ travis logs --pro --debug
** Loading "/Users/iriberri/.travis/config.yml"
** GET "repos/iriberri/travis-experiments"
**   took 0.79 seconds
** GET "builds/" {:number=>"1994", :repository_id=>2337303}
**   took 0.17 seconds
** GET "jobs/117745214"
**   took 0.18 seconds
displaying logs for iriberri/travis-experiments#1994.1
** GET "logs/117786618"
**   took 0.32 seconds
** GET "https://s3.amazonaws.com/archive.travis-ci.com/jobs/117745214/log.txt?X-Amz-Expires=30&X-Amz-Date=xxxx&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxx/xxx/us-east-1/s3/aws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxxxx"
**   took 0.75 seconds
** Storing "/Users/iriberri/.travis/error.log"
undefined method `each_pair' for #<String:0x007fbc8b195e20>
for a full error report, run travis report --pro
```

I redacted parts of the URL above, but it looks like the CLI is accessing an incorrect/expired log file:
```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Request has expired</Message>
  ...
</Error>
```

Not sure if this is a red herring here, but posting just in case.

**Comment by tback** [comment] 2018-04-05 07:09
Same here:

```
travis report --org
System
Ruby:                     Ruby 2.3.3-p222
Operating System:         Debian 9.4
RubyGems:                 RubyGems 2.5.2.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2018-04-05 09:01:12 +0200

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "tback"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `each_pair' for #<String:0x00563522dfb850>
Did you mean?  each_char
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:139:in `load'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:166:in `get'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:319:in `fetch_one'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:128:in `reload'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:208:in `load_attribute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:194:in `relation'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:71:in `block (2 levels) in has'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/artifact.rb:51:in `body'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'
```

**Comment by tback** [comment] 2018-04-10 07:45
it'd be great to get a fix or maybe workaround from travis

**Comment by tback** [comment] 2018-04-10 15:24
I looked through this issue again after venting earlier this morning. 

This is not a solution in itself, it's just the piece that I didn't pick up while skimming through this issue and being unfamiliar with ruby.

The workaround is to patch client/session.rb yourself as suggested and described in https://github.com/travis-ci/travis.rb/issues/578#issuecomment-368142083 .

If you don't know where to find the file run `travis report --org` it'll show you the stacktrace and a path like the following:

`/var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb`

Then you add the `class Hash` at the top of the file and the three lines to the `load` method from from the comment above:

        if data.is_a?(String)
          return { log: { attributes: { body: data }}.to_struct('DummyEntity')}.to_struct('DummyLog')
        end

**Comment by leusonmario** [comment] 2018-04-12 17:19
I also have the same problem.

**Comment by leusonmario** [comment] 2018-05-03 01:46
Any update?

**Comment by jwiegley** [comment] 2018-05-06 19:40
Would also love to see a 1.8.9 release to fix.

**Comment by leusonmario** [comment] 2018-05-07 18:49
@tback I tried your fix, but I got the following problem: `artifact.rb:51:in `body': undefined method `pending?' for nil:NilClass (NoMethodError)`

Would you have any idea about how to fix this new error?

**Comment by adigherman** [comment] 2018-05-07 19:41
@leusonmario did you try https://github.com/travis-ci/travis.rb/issues/578#issuecomment-368936908?

**Comment by leusonmario** [comment] 2018-05-08 12:08
@adigherman Yes, I did the whole process but it didn't work.

**Comment by leusonmario** [comment] 2018-05-08 12:15
@adigherman Thanks. Your solution fixed the problem!

**Comment by textarcana** [comment] 2018-05-30 01:48
I have applied the changes described in this thread, here https://github.com/textarcana/travis.rb/tree/fix-issue-578

That is the 1.8.8 tag with the changes in this thread applied to it. It works on my machine.

The easiest way to install this is with bundler. Add the following to your `Gemfile` then run `bundle install`:

`gem 'travis', :git => 'https://github.com/textarcana/travis.rb.git', :branch => 'fix-issue-578'`

To figure out where bundler put the executable is, type `bundle info`

**Comment by laanwj** [comment] 2018-05-30 15:29
@textarcana Thanks, I applied those changes and it fixed the problem for me. Can finally show long logs again with `travis logs -i 29039.2|less -R` 🎉. Will you file it as PR here, so it  can be merged upstream?

**Comment by 20goto10** [comment] 2018-05-30 15:44
I don't want to get in the way of progress but the original snippet I posted is really a hack. There should be a better solution to this problem. I just didn't have the time to hunt through this code and work it out properly. That having been said... whatever works! Thanks for taking the time to put together a usable branch, @textarcana !

**Comment by textarcana** [comment] 2018-05-31 02:44
@20goto10 yes I too have no idea what the patch _does._

It seems others who have commented here before, have more knowledge of how the gem works?

If we can arrive at a patch that someone who knows how this thing works :) can say is acceptable, I would be more than happy to create a PR and shepherd it through the merging process!

**Comment by 20goto10** [comment] 2018-05-31 15:16
Essentially the patch just forces the data into a Struct it won't choke on later (which manifests as the whole 'each_pair' thing), whenever the data arrives as a String. So what I didn't really look into is why it's arriving sometimes as a String and sometimes not. I'm guessing there's just a spot in the code somewhere where it usually takes the raw API results and puts them into some class, and in the case of these logs it isn't doing it. But I didn't have the patience to hunt that down at the time (and still don't since my own use for this API is a simple internal helper app, nothing enterprise-y). Retrieving the logs would obviously be a major use case for this API so I'm pretty surprised this hasn't been patched properly by now.

**Comment by noahsussman** [comment] 2018-06-01 02:22
> nothing enterprise-y

heh. My needs are enterprise-y like Starfleet :) so I def need the logs command to work and now that you talked a little about what the problem _is,_ I feel ready to take a run at solving it (as time allows).

**Comment by textarcana** [comment] 2018-06-01 02:28
> my own use for this API is a simple internal helper app, nothing enterprise-y

heh. My use for this API is enterprisey like Starfleet :) so I definitely need the `logs` command to work.

I can see how it's an easy workaround and that's probably why no one fixed it up to now?

Anyway now that you have explained a bit I feel I could take a dive into fixing the actual problem (as time allows). 👍

**Comment by woky** [comment] 2018-08-13 09:25
Do you know which was the last version with `logs` working or whether it depends on environment. In other words, does anyone use `logs` with recent version without patching? I'm just curious where the bug originates from.

**Comment by eneko** [comment] 2018-09-04 17:02
This issue seems to still happen with Ruby 2.5.1 and `travis` gem 1.8.9.

```
$ travis logs
displaying logs for {redacted}#2560.1
undefined method `each_pair' for #<String:0x00007faea91cc960>
Did you mean?  each_char
for a full error report, run travis report --pro

$ travis report --pro
System
Ruby:                     Ruby 2.5.1-p57
Operating System:         Mac OS X 10.13.6
RubyGems:                 RubyGems 2.7.6

CLI
Version:                  1.8.9
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2018-09-04 09:50:21 -0700

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "eneko"
Verify SSL:               yes
Enterprise:               no

Endpoints
com:                      https://api.travis-ci.com/ (access token, current)
org:                      https://api.travis-ci.org/ (access token)

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `each_pair' for #<String:0x00007f7f40a22ff8>
Did you mean?  each_char
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/client/session.rb:139:in `load'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/client/session.rb:166:in `get'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/client/session.rb:319:in `fetch_one'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/client/session.rb:128:in `reload'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/client/entity.rb:208:in `load_attribute'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/client/entity.rb:194:in `relation'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/client/entity.rb:71:in `block (2 levels) in has'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/client/artifact.rb:51:in `body'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli/logs.rb:39:in `display_log'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli/logs.rb:23:in `run'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.5.0/gems/travis-1.8.9/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by noahsussman** [comment] 2018-09-10 20:50
@emmasax1 yes! I will create a PR. Thank you!

**Comment by trinitronx** [comment] 2018-10-01 18:29
Testing patch in textarcana#1 on travis gem `1.8.9` with Ruby `2.5.1` still results in same error & stacktrace posted by @eneko.

Function that fails is the line calling `each_pair` here:

      def load(data)
        result = {}
        (data || {}).each_pair do |key, value|
          entity      = load_entity(key, value)
          result[key] = entity if entity
        end
        result
      end

There is a string in one of these data objects which looks like the log output.  This can be observed if you add some print lines right before this to print things out:

      def load(data)
        result = {}
        require 'pp'
        pp data.class
        pp data
        (data || {}).each_pair do |key, value|
          entity      = load_entity(key, value)
          result[key] = entity if entity
        end
        result
      end

```
Hash
[...SNIP...]
Hash
[...SNIP...]
displaying logs for username/reponame#NN.X
String
"travis_fold:start:step_upload_script\r\e[0K\e[33;1mUploading script\e[0m\r\n" +
"travis_fold:end:step_upload_script\r\e[0Ktravis_fold:start:worker_info\r\e[0K\e[33;1mWorker information\e[0m\n" +
"hostname: d516ec12-a65d-4454-ba88-daba63f36213@1.production-1-worker-org-gce-n8qm\n" +
"version: v4.2.0 https://github.com/travis-ci/worker/tree/7d17a81b8afc19da6842f1153f37371e859f4ccd\n" +
"instance: travis-job-1620ef03-61f5-425f-bc2d-edb70fd33148 travis-ci-garnet-trusty-1513287054-2ffda03 (via amqp)\n" +
"startup: 2m3.167309656s\n" +
"travis_fold:end:worker_info\r\e[0Ktravis_fold:start:system_info\r\e[0K\e[33;1mBuild system information\e[0m\r\n" +
"Build language: python\r\n" +
"Build group: edge\r\n" +
"Build dist: trusty\r\n" +
"Build id: 435742078\r\n" +
"Job id: 435742080\r\n" +
"Runtime kernel version: 4.4.0-104-generic\r\n" +
"travis-build version: e1590b459\r\n" +
"\e[34m\e[1mBuild image provisioning date and time\e[0m\r\n" +
"Thu Dec 14 21:58:09 UTC 2017\r\n" +
"\e[34m\e[1mOperating System Details\e[0m\r\n" +
"Distributor ID:\tUbuntu\r\n" +
"Description:\tUbuntu 14.04.5 LTS\r\n" +
"Release:\t14.04\r\n" +
"Codename:\ttrusty\r\n" +
[...SNIP...]
```

This object is a long ruby string with `"text" + " more text " + ...` representing the build log output.  Assumptions based on this are that at some point maybe this was a type supporting `.each_pair`, maybe this code was different, or Travis API output changed?

**Comment by RaVbaker** [comment] 2018-11-27 13:10
I also experience same issue Ruby: 2.5.1 and travis gem version 1.8.9. :/ Any ETA for a fix ?

**Comment by BanzaiMan** [comment] 2018-11-29 13:34
Sorry for the delay, everyone.

@textarcana Do you mind opening a PR with your patch? I somehow missed it completely.

**Comment by OGKevin** [comment] 2018-12-23 08:17
Any update? :(

**Comment by poppyschmo** [comment] 2019-01-11 12:09
Seems there's some recent PR activity.

Been making do with this ugliness, but hopefully not for much longer:
```shell
# Scrape 307 Temporary Redirect response for "Location" header field
# Drop non-printables, less ANSI \e and carriage (Tools::SafeString.colorized)
# "$@" means "the" "rest" (opts/args ...)
curl "$(travis logs --debug-http "$@" | grep ^Location: | cut -d \" -f 2)" | \
    sed 's/[^[:print:]\x1b\r]//g'
```

**Comment by hotdog2201** [comment] 2019-03-21 16:19
Any progress on this? Still getting this when trying to do any travis command such as whoami or encrypt. "undefined method `each_pair' for #<String:0x00000001058240>"

**Comment by markgaensicke** [comment] 2019-09-23 14:01
Any progress on this?

**Comment by adumont** [comment] 2019-09-29 18:48
Same issue here

$ travis report --org
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Ubuntu 16.04
RubyGems:                 RubyGems 2.5.2.1

CLI
Version:                  1.8.10
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2019-09-29 20:48:06 +0200

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "adumont"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `each_pair' for #<String:0x000000022ff088>
Did you mean?  each_char
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/client/session.rb:139:in `load'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/client/session.rb:166:in `get'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/client/session.rb:325:in `fetch_one'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/client/session.rb:128:in `reload'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/client/entity.rb:208:in `load_attribute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/client/entity.rb:194:in `relation'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/client/entity.rb:71:in `block (2 levels) in has'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/client/artifact.rb:51:in `body'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/cli/logs.rb:39:in `display_log'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/cli/logs.rb:23:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.10/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.

**Comment by cryptid11** [comment] 2019-10-28 20:00
shouldnt this having some priority at this point ? :/ btw also for me the @textarcana patch doesnt work!   im gonna use @poppyschmo art XD (thanks)

**Comment by ashutosh108** [comment] 2020-01-18 09:54
It's 2020, but the same bug is still there e.g. for `travis logs`:

```
travis report --com
System
Ruby:                     Ruby 2.7.0-p0
Operating System:         Windows
RubyGems:                 RubyGems 3.1.2

CLI
Version:                  1.8.10
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2020-01-18 11:50:05 +0200

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "ashutosh108"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ ()
com:                      https://api.travis-ci.com/ (access token, default, current)

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `each_pair' for #<String:0x00000000063bf708>
Did you mean?  each_char
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/client/session.rb:139:in `load'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/client/session.rb:166:in `get'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/client/session.rb:325:in `fetch_one'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/client/session.rb:128:in `reload'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/client/entity.rb:208:in `load_attribute'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/client/entity.rb:54:in `block (2 levels)
in attributes'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/client/entity.rb:194:in `relation'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/client/entity.rb:71:in `block (2 levels)
in has'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/client/artifact.rb:51:in `body'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/cli/logs.rb:39:in `display_log'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/cli/logs.rb:23:in `run'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/cli/command.rb:198:in `execute'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/lib/travis/cli.rb:64:in `run'
        from C:/tools/ruby27/lib/ruby/gems/2.7.0/gems/travis-1.8.10/bin/travis:18:in `<top (required)>'
        from C:/tools/ruby27/bin/travis:23:in `load'
        from C:/tools/ruby27/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by kalbert312** [comment] 2020-03-06 21:49
I debugged this today since I'm trying to login to a github enterprise server. It looks like the string is an html error page from the GHE api. The GHE I was trying to login with a token uses SSO and I was seeing a redirect to the SSO page in the debug output of `travis login -X --github-token=TOKEN` along with a 401 response. It never successfully logged in so user id is nil so all the request urls requiring user id are incorrect.

**Comment by JunzhouLiu** [comment] 2020-03-06 22:03
emmmm
```
System
Ruby:                     Ruby 2.5.1-p57
Operating System:         Ubuntu 18.04
RubyGems:                 RubyGems 2.7.6

CLI
Version:                  1.8.11
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2020-03-07 06:02:04 +0800

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "JunzhouLiu"
Verify SSL:               yes
Enterprise:               no

Endpoints
com:                      https://api.travis-ci.com/ (access token, current)
org:                      https://api.travis-ci.org/ (access token)

Last Exception
An error occurred running `travis encrypt-file --pro`:
    ArgumentError: wrong number of arguments (given 1, expected 2)
        from /var/lib/gems/2.5.0/gems/travis-1.8.11/lib/travis/cli/encrypt_file.rb:79:in `env_name'
        from /var/lib/gems/2.5.0/gems/travis-1.8.11/lib/travis/cli/encrypt_file.rb:70:in `decrypt_command'
        from /var/lib/gems/2.5.0/gems/travis-1.8.11/lib/travis/cli/encrypt_file.rb:42:in `run'
        from /var/lib/gems/2.5.0/gems/travis-1.8.11/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.5.0/gems/travis-1.8.11/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.5.0/gems/travis-1.8.11/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'

```

**Comment by BanzaiMan** [comment] 2020-03-06 22:07
@JunzhouLiu That's not the same issue. That one is fixed by #715.

**Comment by JunzhouLiu** [comment] 2020-03-06 22:10
> @JunzhouLiu That's not the same issue. That one is fixed by #715 (and will be released soon).

okey, thank you for your reply !

**Comment by BanzaiMan** [comment] 2020-03-10 16:19
Hello, everyone. Please test 1.8.12.rc1 for a possible fix to this issue. Thank you!

https://github.com/travis-ci/travis.rb/pull/718#issuecomment-597177077

**Closed** 2020-03-18 16:08 UTC
Labels: api, bug

**Comment by BanzaiMan** [comment] 2020-03-18 16:25
It should work now without updating your client.

```sh-session
$ travis logs -r BanzaiMan/travis_production_test
displaying logs for BanzaiMan/travis_production_test#5226.1
Worker information
hostname: b65b0874-2c3e-411b-8729-b7699aea9fcf@1.worker-org-676f4fdd9b-gkwdb.gce-production-2
⋮
Skipping a deployment with the script provider because the current build is a pull request.

Done. Your build exited with 0.
```
