### ISSUE TITLE
Error on travis setup heroku

### ISSUE THREAD

**Issue by androidfred** [travis-ci/travis.rb#266] opened 2015-01-22 09:50 UTC
Any ideas?

<I've run gem update>

```
$ ruby -v
ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-linux]

$ travis version
1.7.5

$ travis setup heroku --explode --debug
** Loading "/home/ubuntu/.travis/config.yml"
** Timeout::Error: execution expired
** Loading gh
** GET "config"
**   took 0.21 seconds
** GitHub API: HEAD /repos/androidfred/lesn
**   took 0.78 seconds
/usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/remote.rb:71:in `generate_response': undefined method `try' for #<Faraday::Env:0x000000039df8e8> (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/normalizer.rb:8:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/parallel.rb:27:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/remote.rb:88:in `request'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/remote.rb:106:in `head'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/travis-1.7.5/lib/travis/cli/repo_command.rb:111:in `detect_api_endpoint'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/travis-1.7.5/lib/travis/cli/repo_command.rb:23:in `setup'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/travis-1.7.5/lib/travis/cli/command.rb:197:in `execute'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/bin/travis:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/bin/travis:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/bin/ruby_executable_hooks:15:in `<main>'


$ travis report
System
Ruby:                     Ruby 2.1.4-p265
Operating System:         Ubuntu 14.04
RubyGems:                 RubyGems 2.4.2

CLI
Version:                  1.7.5
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2015-01-22 08:00:21 +0000

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis setup`:
    NoMethodError: undefined method `try' for #<Faraday::Env:0x000000038e1c20>
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/remote.rb:71:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/normalizer.rb:8:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/parallel.rb:27:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/remote.rb:88:in `request'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/gh-0.13.3/lib/gh/remote.rb:106:in `head'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/travis-1.7.5/lib/travis/cli/repo_command.rb:111:in `detect_api_endpoint'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/travis-1.7.5/lib/travis/cli/repo_command.rb:23:in `setup'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/travis-1.7.5/lib/travis/cli/command.rb:197:in `execute'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/bin/travis:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/bin/travis:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/bin/ruby_executable_hooks:15:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by BanzaiMan** [comment] 2015-01-22 10:36
This looks like a duplicate of #265.

**Comment by androidfred** [comment] 2015-01-22 10:37
Indeed. Sorry about that!

**Closed** 2015-01-22 10:48 UTC
