### ISSUE TITLE
travis logs - undefined method `each_pair'

### ISSUE THREAD

**Issue by NathanGibbs3** [travis-ci/travis.rb#650] opened 2019-01-11 22:14 UTC
To reproduce:
Run travis log form the command line.

Report & Trace:
System
Ruby:                     Ruby 2.3.3-p222
Operating System:         Debian 9.6
RubyGems:                 RubyGems 2.5.2.1

CLI
Version:                  1.8.9
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2019-01-11 22:03:37 +0000

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "NathanGibbs3"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token)
com:                      https://api.travis-ci.com/ (access token, default, current)
staging-org:              https://api-staging.travis-ci.org/ ()

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `each_pair' for #<String:0x10ce260>
Did you mean?  each_char
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/client/session.rb:139:in `load'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/client/session.rb:166:in `get'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/client/session.rb:319:in `fetch_one'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/client/session.rb:128:in `reload'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/client/entity.rb:208:in `load_attribute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/client/entity.rb:194:in `relation'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/client/entity.rb:71:in `block (2 levels) in has'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/client/artifact.rb:51:in `body'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/cli/logs.rb:39:in `display_log'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/cli/logs.rb:23:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.9/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'

**Comment by auscompgeek** [comment] 2019-01-15 00:36
I'm also getting this with Ruby 2.6.0.

**Comment by stvhwrd** [comment] 2019-02-06 07:10
Ditto.  Here's mine:

❯❯❯ travis report --pro 
System
Ruby:                     Ruby 2.3.7-p456
Operating System:         Mac OS X 10.14.3
RubyGems:                 RubyGems 2.5.2.3

CLI
Version:                  1.8.9
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2019-02-05 23:08:50 -0800

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "stvhwrd"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token)
com:                      https://api.travis-ci.com/ (access token, current)

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `each_pair' for #<String:0x00007faa35042bd0>
Did you mean?  each_char
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/client/session.rb:139:in `load'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/client/session.rb:166:in `get'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/client/session.rb:319:in `fetch_one'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/client/session.rb:128:in `reload'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/client/entity.rb:208:in `load_attribute'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/client/entity.rb:194:in `relation'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/client/entity.rb:71:in `block (2 levels) in has'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/client/artifact.rb:51:in `body'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/cli/logs.rb:39:in `display_log'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/cli/logs.rb:23:in `run'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/lib/travis/cli.rb:64:in `run'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/gems/travis-1.8.9/bin/travis:18:in `<top (required)>'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/bin/travis:22:in `load'
        from /usr/local/Cellar/travis/1.8.9_3/libexec/bin/travis:22:in `<main>'

**Comment by abstratt** [comment] 2019-02-14 13:22
Duplicate of #578

**Closed** 2020-03-13 18:37 UTC
