### ISSUE TITLE
travis console behind corporate proxy

### ISSUE THREAD

**Issue by adriens** [travis-ci/travis.rb#312] opened 2015-08-19 03:56 UTC
Hi,

can you pleas provide some guidelines on how to use travis console behind a corporate proxy ?

Thank you in advance for your help.

Best Regards,

Adrien

**Comment by rkh** [comment] 2015-08-24 14:50
What kind of proxy? HTTP proxy?

**Comment by adriens** [comment] 2015-08-24 19:27
Hi, yes, sorry, HTTP proxy. my http_proxy and https_proxy variables are set (linux) but it seems like they have no effect on travis console.

**Comment by rkh** [comment] 2015-09-03 16:15
Yes, I think the CLI just ignores them atm.

**Comment by adriens** [comment] 2015-09-03 19:25
@rkh : is there any workaround ?

**Comment by FloFra** [comment] 2015-10-20 12:37
Duplicate of #262.

**Closed** 2016-01-09 05:41 UTC
