### ISSUE TITLE
encrypt-file fails with "resource not found"

### ISSUE THREAD

**Issue by Bilge** [travis-ci/travis.rb#237] opened 2014-10-10 22:13 UTC
`travis encrypt-file .file` yields the following:

>
encrypting .file for foo/bar
storing result as .file.enc
DANGER ZONE: Override existing .file? |no| y
storing secure env variables for decryption
resource not found ({"error":"Couldn't find repository"})

I have no idea what this error means or how to overcome it. Google search yields nothing. I am running this command from the foo/bar repository local checkout directory.

For what it's worth, `travis encrypt` works fine for the same repository.

**Comment by bill-auger** [comment] 2015-04-13 00:26
has this issue been resolved - i am getting same error

i first had the same issue as #199 with "Validation Failed" - after i resolved that by  deleting the personal access token i am able to get through as far as
```
Encrypt API key? |yes| y
resource not found ({"file":"not found"})
```
then it quits and i need to delete the personal access token again or else i can not get past the login phase again

as the OP of this issue if i generate another token but the ```travis encrypt``` command give the same "resource not found" error - i have tried to re-sync the repo from the website but this did not seem to help

**Comment by rkh** [comment] 2015-04-13 16:20
> `GET "repos/nnnnnnn/key"`

Did you replace the ID with `n`s?

**Comment by bill-auger** [comment] 2015-04-13 16:26
yes i replaced the ID by hand before posting - i was a seven digit number

**Comment by bill-auger** [comment] 2015-04-13 17:54
@rkh - if you still with me here - just wanted to add this

the resource that is not found is obviously the one returned by travis pubkey command

$ travis pubkey
resource not found ({"file":"not found"})

the thing that strikes me though is that there seems to be no concept of a "repo public key" at least not accessible via the github website - perhaps it is burried deep in the github API or perhaps this is referring to oAuth tokens - or perhaps the key in question may be the one discussed in issue #199 - but that is a "personal access token" that is associated with a user account not a specific repo - you find this under "personal access tokens" in your user settings - the only association of travis with the specific repo is the "Third-party application access policy" which is just a switch

to be clear these repos are not directly associated with my user - they belong to an organization of which i am admin - perhaps the issue lies there

**Comment by khadrin** [comment] 2015-04-13 18:43
Hi. I'm having the same issue:

```
$ travis pubkey -d
** Loading "/Users/stephensmith/.travis/config.yml"
** Timeout::Error: execution expired
** GET "repos/mantacode/aws-cache"
**   took 0.078 seconds
** GET "repos/4487336/key"
**   took 0.086 seconds
resource not found ({"file":"not found"})
```

It's preventing me from encrypting a secret for `.travis.yml`.

**Comment by rkh** [comment] 2015-04-13 19:15
Is this for a private repo? If so, can you email the output with the ID to support@travis-ci.com?

**Comment by bill-auger** [comment] 2015-04-13 19:21
mine is public so that means the id is public yes? - do you want the output of ```travis encrypt``` or ```travis pubkey``` ?

**Comment by rkh** [comment] 2015-04-13 20:23
ID is public in that case, yes. Just the ID would be sufficient.

**Comment by bill-auger** [comment] 2015-04-13 20:32
the repo ID is 4467571 - i posted the full output including ID about an hour ago as an edit to my last post  - you must be answering these via email so you would not have noticed that -  if you are actively addressing this issue right now it may be helpful if you could join the IRC channel on freenode

**Comment by rkh** [comment] 2015-04-13 20:50
Yes, sorry, answered from the email. I can reproduce the issue and will be investigating tomorrow.

**Comment by bill-auger** [comment] 2015-04-13 21:08
ok great i would like to see this feature working as it is an integral part of the ```travis setup releases``` feature - please keep us posted here and hopefully close this issue soon

**Comment by skierkowski** [comment] 2015-04-14 03:29
Seems like this issue became quite popular over the past 12 hours. Might be a bit redundant, but thought I'd share my issue too. Running any command (e.g. `encrypt`, `pubkey` or even [node-travis-encrypt](https://github.com/pwmckenna/node-travis-encrypt)) that hits the API `/repos/4482545/key` throws that error for me on `travis-1.7.6`. This is a public repo, here is what I get on ` travis raw /repos/4482545/key --debug`.

    ** Loading "/Users/maciej/.travis/config.yml"
    ** GET "repos/4482545/key"
    **   took 0.13 seconds
    resource not found

**Comment by rkh** [comment] 2015-04-14 08:24
This seems to not actually be an issue with the client or the API. For some reason these repos don't have a key associated with them. Of course, the error handling for this could be better, but that would only fight the symptom, not the cause.

**Comment by bill-auger** [comment] 2015-04-14 16:34
this is also open issue 3647 on the travis-ci repo https://github.com/travis-ci/travis-ci/issues/3647

**Comment by bill-auger** [comment] 2015-04-15 16:47
@rkh  - i believe this issue is resolved per https://github.com/travis-ci/travis-ci/issues/3647

**Closed** 2015-04-16 13:26 UTC

**Comment by furushchev** [comment] 2016-09-06 10:26
I'm getting the same error while running `travis sshkey --generate -r <org>/<repo> --pro`.
Here is debug log:

```bash
$ travis --version
1.8.2
$ travis sshkey --generate -r <org>/<repo> --pro --debug
** Loading "/home/furushchev/.travis/config.yml"
** Timeout::Error: execution expired
** GET "repos/<org>/<repo>"
**   took 1.3 seconds
** Loading gh
** GET "config"
**   took 0.2 seconds
We need the GitHub login for the account you want to add the key to.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Username: furushchev
Password for furushchev: *******
** GitHub API: GET /user?per_page=100
**   took 1.3 seconds
** GitHub API: GET /user?per_page=100
**   took 1 seconds
** GitHub API: GET /repos/<org>/<repo>?per_page=100
**   took 1.1 seconds

Generating RSA key.
Uploading public key to GitHub.
** GitHub API: POST /user/keys
**   took 1.1 seconds
Uploading private key to Travis CI.
** PATCH "settings/ssh_key/1935065" "{\"ssh_key\":{\"value\":\"<ssh key hidden>",\"description\":\"key for fetching dependencies for <org>/<repo> via furushchev\"}}"
**   took 0.52 seconds
resource not found ({"error":"Couldn't find repository"})
```

**Comment by the-frey** [comment] 2017-02-14 11:26
I'm seeing the same error as @furushchev with a pro account. `travis endpoint` gives:

     API endpoint: https://api.travis-ci.org/

But I've been adding the `--pro` flag to the `travis sshkey` command, so not sure what's going on.

**Comment by the-frey** [comment] 2017-02-14 11:29
In fact, even if you run:

    travis endpoint --pro --set-default

The subsequent command to `travis sshkey --generate -r myorg/repo --debug` fails with the same error:

    resource not found ({"error":"Couldn't find repository"})
