### ISSUE TITLE
uninitialized constant GH::Error

### ISSUE THREAD

**Issue by retog** [travis-ci/travis.rb#253] opened 2014-12-02 10:42 UTC
I'm getting an error like the following with any trais command I tried (except `travis report`). I'm using ubuntu. I first noticewd the problem after it told me that I had to update (using gem). After that I made sure I was using the latest ruby by following the installation instructions in the README.

```
$ travis init
uninitialized constant GH::Error
for a full error report, run travis report

$ travis report
System
Ruby:                     Ruby 2.1.4-p265
Operating System:         Ubuntu 14.04
RubyGems:                 RubyGems 2.2.2

CLI
Version:                  1.7.4
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2014-12-02 11:06:11 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis init`:
    NameError: uninitialized constant GH::Error
        from /var/lib/gems/2.1.0/gems/travis-1.7.4/lib/travis/cli/repo_command.rb:110:in `rescue in detect_api_endpoint'
        from /var/lib/gems/2.1.0/gems/travis-1.7.4/lib/travis/cli/repo_command.rb:106:in `detect_api_endpoint'
        from /var/lib/gems/2.1.0/gems/travis-1.7.4/lib/travis/cli/repo_command.rb:23:in `setup'
        from /var/lib/gems/2.1.0/gems/travis-1.7.4/lib/travis/cli/command.rb:197:in `execute'
        from /var/lib/gems/2.1.0/gems/travis-1.7.4/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.1.0/gems/travis-1.7.4/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'
```

**Comment by Mailaender** [comment] 2015-01-01 20:41
I can confirm that this helps. Had to update both https://build.opensuse.org/request/show/266982 and https://build.opensuse.org/request/show/266985 to get rid of the error.

**Comment by JamesKyburz** [comment] 2016-10-31 08:49
Just got this and it was also fixed by running

```
gem update backports
```

be it with [sudo](https://xkcd.com/149/)

**Comment by BanzaiMan** [comment] 2020-03-23 17:51
Possibly a duplicate of #247. Closing as stale. Please open a new issue if you see this again.

**Closed by BanzaiMan** 2020-03-23 17:51 UTC
